prodtype: ocp4

title: "Check config map test value exists - namespace default"

# NOTE(jaosorior): this required a remediation that's written in go as opposed
# to being a script like the ocp4 e2e remediations usually are... This
# remediation doesn't work in the "moderate" profile, so this needs to be
# figured out.

description: |-
  Checking config map value for test

rationale: |-
  Checking config map value for test

identifiers:
  cce@ocp4: CCE-84088-4


references:
  cis: 3.1.1

severity: medium

warnings:
- general: |-
    {{{ openshift_cluster_setting("/apis/config.openshift.io/v1/oauths/cluster") | indent(4) }}}

# NOTE(jaosorior): Here we're testing that ANYTHING has been set in
# the identityProvidres section. We only care that it has been
# configured to something.
template:
  name: yamlfile_value
  vars:
    ocp_data: 'true'
    filepath: /api/v1/namespaces/default/configmaps/compliance-check
    yamlpath: ".data.test"
    entity_check: "at least one"
    values:
    - value: ".*"
      operation: "pattern match"
